apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: customer-analysis-cluster
  region: us-east-1
  version: "1.35"

# AWS Academy: Use LabRole for cluster and nodes
iam:
  serviceRoleARN: arn:aws:iam::211125559404:role/c204605a5216167l14425323t1w211125-LabEksClusterRole-E3y3HOFIXQFi

managedNodeGroups:
  - name: ai-nodes
    instanceType: t3.large
    desiredCapacity: 3
    minSize: 3
    maxSize: 5
    volumeSize: 30
    # AWS Academy: Use LabRole for node group
    iam:
      instanceRoleARN: arn:aws:iam::211125559404:role/c204605a5216167l14425323t1w211125559-LabEksNodeRole-kXfaOiQ9Zmzw
    tags:
      Project: AI-Cluster
      Environment: Lab

# Addons
addons:
  - name: vpc-cni
    version: latest
  - name: coredns
    version: latest
  - name: kube-proxy
    version: latest
