apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-service
  labels:
    app: data-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: data-service
  template:
    metadata:
      labels:
        app: data-service
    spec:
      containers:
      - name: data-service
        image: 022655255269.dkr.ecr.us-east-1.amazonaws.com/data-service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8001
        env:
        - name: DATABASE_URL
          value: "postgresql://postgres:postgres123@sentiments-db.c1cg6my0wm53.us-east-1.rds.amazonaws.com:5432/sentiments"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: data-service
spec:
  type: ClusterIP
  selector:
    app: data-service
  ports:
  - protocol: TCP
    port: 8001
    targetPort: 8001
